[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
PORT = "8000"
RAILWAY_DOCKERFILE_PATH = "docker/Dockerfile.railway"