version: '3.8'

services:
  # Main API service - REQUIRED
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Railway will provide REDIS_URL automatically when you add Redis addon
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - TESSERACT_PATH=/usr/bin/tesseract
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE=10485760
      - MAX_CONCURRENT_JOBS=5  # Reduced for Railway's free tier
      - CORS_ORIGINS=["*"]
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
      - ../templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M  # Railway free tier limit
          cpus: '0.5'

  # Redis - RECOMMENDED (or use Railway's Redis addon)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

volumes: {}
networks:
  default:
    driver: bridge