version: '3.8'

services:
  # Main API service
  api:
    build: 
      context: ..
      dockerfile: docker/dockerfile.light  # Use lightweight version
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TESSERACT_PATH=/usr/bin/tesseract
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE=10485760
      - MAX_CONCURRENT_JOBS=5
      - CORS_ORIGINS=["*"]
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
      - ../templates:/app/templates
    depends_on:
      - redis
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes: {}